disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Cooroora - whats happening."

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "A blog for Cooroora Rise"

  [params.author]
  name = "Darrell Mayson"
  image = "me-face-peanuts-cartoon.png"
  headline = "Blog owner, maintainer and fiddler."
  links = [
    { twitter = "https://twitter.com/monkeysh1ne"},
    { github = "https://github.com/monkeysh1ne" }
    ]
  
