# netlify.toml

[build]
  command = "hugo mod get -u && hugo --gc --minify -b $URL"
  publish = "public"
  command = "hugo --minify"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.22.2"
  TZ = "Australia/Brisbane (AEST, +1000)"  # Set to preferred timezone

[context.production.environment]
  HUGO_VERSION = "0.153.0"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.153.0"